name: PHP Composer

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        php_version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']

    runs-on: ubuntu-latest
    container:
      image: "lephare/php:${{ matrix.php_version }}"

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php_version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php_version }}-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: |
        composer lint
        composer test
